config/routes.rb
Rails.application.routes.draw do
  root "homes#home"
  get "/about", to: "homes#about"
  get "/contact", to: "homes#contact"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users
  resources :songs
  resources :comments, only: [:new, :create]
  resources :ratings, only: [:new, :create, :show]
  resources :genres

  namespace :admin do
    root "homes#index"
    resources :users, except: [:edit, :update]
    resources :genres
    resources :artists
    resources :songs, only: [:index, :destroy]
  end
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs, dependent: :destroy
  validates :name, presence: true, uniqueness: {case_sensitive: false},
    length: {maximum: Settings.artistname.maximum}
  validates :description, presence: true
  scope :search, ->search{where "name LIKE ?", "%#{search}%"}
end

app/controllers/admin/artists_controller.rb
class Admin::ArtistsController < ApplicationController
  before_action :logged_in_user, :verify_admin!
  before_action :load_artist, except: [:new, :create, :index]
  before_action :load_page, only: [:index]
  layout "admin"

  def index
    if request.xhr?
      @artists = Artist.search(params[:name]).includes(:songs).select(:id, :name)
        .order(name: :asc).paginate page: params[:page], per_page: Settings.paginate.per_page
      render json: {
        search_result: render_to_string(@artists)
      }, status: :ok
    else
      @artists = Artist.includes(:songs).select(:id, :name).order(name: :asc)
        .paginate page: params[:page], per_page: Settings.paginate.per_page
    end
  end

  def show
    @songs = @artist.songs.includes(:artist, :genre)
      .select(:id, :name, :artist_id, :user_id, :genre_id, :picture, :file, :total_score)
      .order(name: :asc).paginate page: params[:page],
      per_page: Settings.paginate.per_page
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new artist_params
    if @artist.save
      flash[:success] = t ".success"
      redirect_to admin_artists_url
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @artist.update_attributes artist_params
      flash[:success] = t ".success"
      redirect_to admin_artist_url(@artist)
    else
      render :edit
    end
  end

  def destroy
    if @artist.destroy
      flash[:success] = t ".success"
    else
      flash[:danger] = t ".fail"
    end
    redirect_to admin_artists_url
  end

  private
  def artist_params
    params.require(:artist).permit :name, :description
  end

  def load_artist
    @artist = Artist.find_by id: params[:id]
  end
end

app/views/admin/artists/_artist.html.erb
<tr>
  <td><%= @page * Settings.paginate.per_page + artist_counter - 4 %></td>
  <td><%= link_to artist.name, admin_artist_path(artist) %></td>
  <td><%= artist.songs.size %></td>
  <td>
    <%= link_to edit_admin_artist_path(artist) do %>
      <span class="glyphicon glyphicon-pencil btn-xs btn-warning"></span>
    <% end %>
    <%= link_to admin_artist_path(artist), method: :delete,
      data: {confirm: t("confirm")} do %>
      <span class="glyphicon glyphicon-trash btn-xs btn-danger"></span>
    <% end %>
  </td>
</tr>

app/views/admin/artists/_artist_form.html.erb
<%= form_for [:admin, artist] do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <%= f.label :name, t(".artist_name") %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :description, t(".artist_description") %>
  <%= f.text_area :description, class: "form-control" %>

  <%= f.submit yield(:submit) , class: "btn btn-primary submit" %>
<% end %>

app/views/admin/artists/edit.html.erb
<% provide :title, t(".title") %>
<% provide :submit, t(".edit") %>
<h1><%= t ".title" %></h1>
<div class="col-md-6 col-md-offset-3">
  <%= render "artist_form", artist: @artist %>
</div>

app/views/admin/artists/index.html.erb
<% provide :title, t(".manage_artists") %>
<% provide :placeholder, t(".search_artists") %>
<h1><%= t (".manage_artists") %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_tag admin_artists_path, method: :get do %>
      <%= render "shared/search" %>
    <% end %>
  </div>
</div>
<div class="container">
  <table class="table">
    <thead>
      <tr>
        <th>#</th>
        <th><%= t "name" %></th>
        <th><%= t "total_song" %></th>
        <th><%= t "action" %></th>
      </tr>
    </thead>
    <tbody class="list-table">
      <%= render @artists %>
    </tbody>
  </table>
  <div class=" plus-edit">
    <i class="glyphicon glyphicon-plus"></i>
    <%= link_to t(".add_artist"), new_admin_artist_path %>
  </div>
  <%= will_paginate %>
</div>

app/views/admin/artists/new.html.erb
<% provide :title, t(".title") %>
<% provide :submit, t(".create") %>
<h1><%= t ".title" %></h1>
<div class="col-md-6 col-md-offset-3">
  <%= render "artist_form", artist: @artist %>
</div>

app/views/admin/artists/show.html.erb
<% provide :title, t(".title") %>
<h1><%= @artist.name %></h1>
<h2><%= @artist.description %></h2>
<div class="row">
  <%= render partial: "shared/song_list", collection: @songs, as: "song" %>
</div>
<%= will_paginate @songs %>