config/routes.rb
Rails.application.routes.draw do
  root "homes#home"
  get "/about", to: "homes#about"
  get "/contact", to: "homes#contact"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users
  resources :songs
  resources :comments, only: [:new, :create]
  resources :ratings, only: [:new, :create, :show]
  resources :genres

  namespace :admin do
    root "homes#index"
    resources :users, except: [:edit, :update]
    resources :genres
    resources :artists
    resources :songs, only: [:index, :destroy]
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :songs, dependent: :destroy
  validates :name, presence: true, uniqueness: {case_sensitive: false},
    length: {maximum: Settings.genrename.maximum}
  validates :description, presence: true

  scope :search, ->search{where "name LIKE ?", "%#{search}%"}
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :logged_in_user, :verify_admin!
  before_action :load_genre, except: [:new, :create, :index]
  before_action :load_page, only: [:index]
  layout "admin"

  def index
    if request.xhr?
      @genres = Genre.search(params[:name]).includes(:songs).select(:id, :name)
        .order(name: :asc).paginate page: params[:page], per_page: Settings.paginate.per_page
      render json: {
        search_result: render_to_string(@genres)
      }, status: :ok
    else
      @genres = Genre.includes(:songs).select(:id, :name).order(name: :asc)
        .paginate page: params[:page], per_page: Settings.paginate.per_page
    end
  end

  def show
    @songs = @genre.songs.includes(:artist, :genre)
      .select(:id, :name, :artist_id, :user_id, :genre_id, :picture, :file, :total_score)
      .order(name: :asc).paginate page: params[:page],
      per_page: Settings.paginate.per_page
  end

  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new genre_params
    if @genre.save
      flash[:success] = t ".success"
      redirect_to admin_genres_url
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @genre.update_attributes genre_params
      flash[:success] = t ".success"
      redirect_to admin_genre_url(@genre)
    else
      render :edit
    end
  end

  def destroy
    if @genre.destroy
      flash[:success] = t ".success"
    else
      flash[:danger] = t ".fail"
    end
    redirect_to admin_genres_url
  end

  private
  def genre_params
    params.require(:genre).permit :name, :description
  end

  def load_genre
    @genre = Genre.find_by id: params[:id]
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genres = Genre.includes(:songs).select(:id, :name).order(name: :asc)
      .paginate page: params[:page], per_page: Settings.paginate.per_page
  end

  def show
    @genre = Genre.find_by id: params[:id]
    @songs = @genre.songs.includes(:artist, :genre)
      .select(:id, :name, :artist_id, :user_id, :genre_id, :picture, :file, :total_score)
      .order(name: :asc).paginate page: params[:page],
      per_page: Settings.paginate.per_page
  end
end

app/views/admin/genres/_genre.html.erb
<tr>
  <td><%= @page * Settings.paginate.per_page + genre_counter - 4 %></td>
  <td><%= link_to genre.name, admin_genre_path(genre) %></td>
  <td><%= genre.songs.size %></td>
  <td>
    <%= link_to edit_admin_genre_path(genre) do %>
      <span class="glyphicon glyphicon-pencil btn-xs btn-warning"></span>
    <% end %>
    <%= link_to admin_genre_path(genre), method: :delete,
      data: {confirm: t("confirm")} do %>
      <span class="glyphicon glyphicon-trash btn-xs btn-danger"></span>
    <% end %>
  </td>
</tr>

app/views/admin/genres/_genre_form.html.erb
<%= form_for [:admin, genre] do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <%= f.label :name, t(".genre_name") %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :description, t(".genre_description") %>
  <%= f.text_area :description, class: "form-control" %>

  <%= f.submit yield(:submit) , class: "btn btn-primary submit" %>
<% end %>

app/views/admin/genres/edit.html.erb
<% provide :title, t(".title") %>
<% provide :submit, t(".edit") %>
<h1><%= t ".title" %></h1>
<div class="col-md-6 col-md-offset-3">
  <%= render "genre_form", genre: @genre %>
</div>

app/views/admin/genres/index.html.erb
<% provide :title, t(".manage_genres") %>
<% provide :placeholder, t(".search_genres") %>
<h1><%= t (".manage_genres") %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_tag admin_genres_path, method: :get do %>
      <%= render "shared/search" %>
    <% end %>
  </div>
</div>

<div class="container">
  <table class="table">
    <thead>
      <tr>
        <th>#</th>
        <th><%= t "name" %></th>
        <th><%= t "total_song" %></th>
        <th><%= t "action" %></th>
      </tr>
    </thead>
    <tbody class="list-table">
      <%= render @genres %>
    </tbody>
  </table>
  <div class=" plus-edit">
    <i class="glyphicon glyphicon-plus"></i>
    <%= link_to t(".add_genre"), new_admin_genre_path %>
  </div>
  <%= will_paginate %>
</div>

app/views/admin/genres/new.html.erb
<% provide :title, t(".title") %>
<% provide :submit, t(".create") %>
<h1><%= t ".title" %></h1>
<div class="col-md-6 col-md-offset-3">
  <%= render "genre_form", genre: @genre %>
</div>

app/views/admin/genres/show.html.erb
<% provide :title, t(".title") %>
<h1><%= @genre.name %></h1>
<h2><%= @genre.description %></h2>
<%= render partial: "songs/song", collection: @songs, as: "song" %>