config/routes.rb
Rails.application.routes.draw do
  root "homes#home"
  get "/about", to: "homes#about"
  get "/contact", to: "homes#contact"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users
  resources :songs
  resources :comments, only: [:new, :create]
  resources :ratings, only: [:new, :create, :show]
  resources :genres

  namespace :admin do
    root "homes#index"
    resources :users, except: [:edit, :update]
    resources :genres
    resources :artists
    resources :songs, only: [:index, :destroy]
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :logged_in_user, :verify_admin!
  layout "admin"

  def index
    @supports = Supports::AdminCount.new
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def home
    @genres = Genre.includes(:songs).select(:id, :name)
  end
end

app/views/admin/homes/index.html.erb
<% provide :title, t(".admin") %>
<h1><%= t ".admin" %></h1>
<div class="row">
  <div class="col-lg-3 col-md-6">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-3">
            <i class="fa fa-list-alt fa-5x"></i>
          </div>
          <div class="col-xs-9 text-right">
            <div class="huge"><%= @supports.genres_count %></div>
            <div><%= t ".genres" %></div>
          </div>
        </div>
      </div>
      <a href="#">
        <div class="panel-footer">
          <span class="pull-left">
            <%= link_to t(".view_details"), admin_genres_path %>
          </span>
          <span class="pull-right">
            <i class="fa fa-arrow-circle-right"></i>
          </span>
          <div class="clearfix"></div>
        </div>
      </a>
    </div>
  </div>
   <div class="col-lg-3 col-md-6">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-3">
            <i class="fa fa-music fa-5x"></i>
          </div>
          <div class="col-xs-9 text-right">
            <div class="huge"><%= @supports.songs_count %></div>
            <div><%= t ".songs" %></div>
          </div>
        </div>
      </div>
      <a href="#">
        <div class="panel-footer">
          <span class="pull-left">
            <%= link_to t(".view_details"), admin_songs_path %>
          </span>
          <span class="pull-right">
            <i class="fa fa-arrow-circle-right"></i>
          </span>
          <div class="clearfix"></div>
        </div>
      </a>
    </div>
  </div>
   <div class="col-lg-3 col-md-6">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-3">
            <i class="fa fa-address-card-o fa-5x"></i>
          </div>
          <div class="col-xs-9 text-right">
            <div class="huge"><%= @supports.artists_count %></div>
            <div><%= t ".artists" %></div>
          </div>
        </div>
      </div>
      <a href="#">
        <div class="panel-footer">
          <span class="pull-left">
            <%= link_to t(".view_details"), admin_artists_path %>
          </span>
          <span class="pull-right">
            <i class="fa fa-arrow-circle-right"></i>
          </span>
          <div class="clearfix"></div>
        </div>
      </a>
    </div>
  </div>
   <div class="col-lg-3 col-md-6">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-3">
            <i class="fa fa-users fa-5x"></i>
          </div>
          <div class="col-xs-9 text-right">
            <div class="huge"><%= @supports.users_count %></div>
            <div><%= t ".users" %></div>
          </div>
        </div>
      </div>
      <a href="#">
        <div class="panel-footer">
          <span class="pull-left">
            <%= link_to t(".view_details"), admin_users_path %>
          </span>
          <span class="pull-right">
            <i class="fa fa-arrow-circle-right"></i>
          </span>
          <div class="clearfix"></div>
        </div>
      </a>
    </div>
  </div>
</div>