config/routes.rb
Rails.application.routes.draw do
  root "homes#home"
  get "/about", to: "homes#about"
  get "/contact", to: "homes#contact"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users
  resources :songs
  resources :comments, only: [:new, :create]
  resources :ratings, only: [:new, :create, :show]
  resources :genres

  namespace :admin do
    root "homes#index"
    resources :users, except: [:edit, :update]
    resources :genres
    resources :artists
    resources :songs, only: [:index, :destroy]
  end
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :user
  belongs_to :genre
  belongs_to :artist
  has_many :comments, dependent: :destroy
  has_many :ratings, dependent: :destroy
  mount_uploader :file, FileUploader
  mount_uploader :picture, PictureUploader

  validates :name, presence: true,
    length: {maximum: Settings.songname.maximum}
  validates :lyric, presence: true
  validates :file, presence: true
  validates :picture, presence: true

  scope :search, ->search{where "name LIKE ?", "%#{search}%"}
end

app/controllers/admin/songs_controller.rb
class Admin::SongsController < ApplicationController
  before_action :logged_in_user, :verify_admin!
  before_action :load_page, only: [:index]
  layout "admin"

  def index
    if request.xhr?
      @songs = Song.search(params[:name]).includes(:artist, :genre)
        .select(:id, :name, :artist_id, :user_id, :genre_id, :picture, :file)
        .order(name: :asc).paginate page: params[:page],
        per_page: Settings.paginate.per_page
      render json: {
        search_result: render_to_string(@songs)
      }, status: :ok
    else
      @songs = Song.includes(:artist, :genre)
        .select(:id, :name, :artist_id, :user_id, :genre_id, :picture, :file)
        .order(name: :asc).paginate page: params[:page],
        per_page: Settings.paginate.per_page
    end
  end

  def destroy
    @song = Song.find_by id: params[:id]
    if @song.destroy
      flash[:success] = t ".delete"
    else
      flash[:danger] = t ".delete_fail"
    end
    redirect_to admin_songs_url
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :logged_in_user, except: [:show, :index]
  before_action :load_artist_genre, except: [:show, :index, :destroy]
  before_action :load_song, except: [:index, :new, :create]
  before_action :correct_user_song, only: [:edit, :update, :destroy]

  def index
    if params[:q]
      @songs = Song.search(params[:q]).includes(:artist, :genre)
        .select(:id, :name, :artist_id, :user_id, :genre_id, :picture, :file, :total_score)
        .order(name: :asc).paginate page: params[:page],
        per_page: Settings.paginate.per_page
    else
      if logged_in?
        @songs = current_user.songs.includes(:artist, :genre)
          .select(:id, :name, :artist_id, :genre_id, :user_id, :picture, :file, :total_score)
          .order(name: :asc).paginate page: params[:page],
          per_page: Settings.paginate.per_page
      else
        @songs = Song.includes(:artist, :genre)
        .select(:id, :name, :artist_id, :user_id, :genre_id, :picture, :file, :total_score)
        .order(name: :asc).paginate page: params[:page],
        per_page: Settings.paginate.per_page
      end
    end
  end

  def show
    return unless current_user
    @comment = current_user.comments.build
    @rating = @song.ratings.find_or_initialize_by user_id: current_user.id
  end

  def new
    @song = current_user.songs.build
  end

  def create
    @song = current_user.songs.build song_params
    if @song.save
      flash[:success] = t ".song_upload"
      redirect_to @song
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @song.update_attributes song_params
      flash[:success] = t ".success"
      redirect_to @song
    else
      render :edit
    end
  end

  def destroy
    if @song.destroy
      flash[:success] = t ".delete"
    else
      flash[:danger] = t ".delete_fail"
    end
    redirect_to songs_url
  end

  private
  def song_params
    params.require(:song).permit :name, :lyric, :file, :artist_id,
      :genre_id, :picture
  end

  def load_artist_genre
    @artists = Artist.all.map{|artist| [artist.name, artist.id]}
    @genres = Genre.all.map{|genre| [genre.name, genre.id]}
  end

  def load_song
    @song = Song.find_by id: params[:id]
    return if @song
    flash[:danger] = t "none_song"
    redirect_to root_url
  end

  def correct_user_song
    return if current_user == @song.user || current_user.is_admin?
    flash[:danger] = t "can_not"
    redirect_to root_url
  end
end

app/views/songs/_song.html.erb
<li class="song-li">
  <div class="col-md-4">
    <div class="song-details">
      <h3>
        <span class="song-name"><%= link_to song.name, song_path(song) %></span> -
        <span><%= song.artist.name %></span>
      </h3>
    </div>
    <%= image_tag(song.picture, class: "picture-song") %>
    <audio controls>
      <source src="<%= song.file %>" type="audio/mpeg">
    </audio>
  </div>
  <div class="col-md-8">
    <% if logged_in? %>
      <% if current_user == song.user || current_user.is_admin? %>
        <div class="btn-group">
          <a class="btn dropdown-toggle btn-info btn-edit-song" data-toggle="dropdown" href="#">
            <i class="glyphicon glyphicon-cog"></i>
          </a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to t("edit"), edit_song_path(song) %>
            </li>
            <li>
              <%= link_to t("delete"), song_path(song), method: :delete,
                data: {confirm: t("confirm")} %>
            </li>
          </ul>
        </div>
      <% end %>
    <% end %>
  </div>
</li>

app/views/songs/_song_form.html.erb
<%= form_for song do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :lyric %>
  <%= f.text_area :lyric, class: "form-control" %>

  <div class="form-group">
    <%= f.label :artist %>
    <%= f.select :artist_id, artists, {}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :genre %>
    <%= f.select :genre_id, genres, {}, class: "form-control" %>
  </div>

  <%= f.label :file %>
  <%= f.file_field :file %>

  <%= f.label :picture %>
  <%= f.file_field :picture %>

  <%= f.submit yield(:submit) , class: "btn btn-primary" %>
<% end %>

app/views/songs/edit.html.erb
<% provide :title, t(".title") %>
<% provide :submit, t(".title") %>
<h1><%= t ".title" %></h1>
<div class="col-md-6 col-md-offset-3">
  <%= render "song_form", song: @song, artists: @artists,
    genres: @genres %>
</div>

app/views/songs/index.html.erb
<% provide :title, t(".title") %>
<h1><%= t ".title" %></h1>
<div class="row">
  <% if @songs.present? %>
    <%= render partial: "shared/song_list", collection: @songs, as: "song" %>
  <% else %>
    <h4><%= t "no_result" %> <span class="red-mark"><%= params[:q] %></span></h4>
    <ul class="search-index">
      <%= t ".suggest" %>
      <li><span><%= t ".suggest1" %></span></li>
      <li><span><%= t ".suggest2" %></span></li>
      <li><span><%= t ".suggest3" %></span></li>
      <li><span><%= t ".suggest4" %></span></li>
    </ul>
  <% end %>
</div>
<%= will_paginate %>

app/views/songs/new.html.erb
<% provide :title, t(".title") %>
<% provide :submit, t("upload") %>
<h1><%= t ".title" %></h1>
<div class="col-md-6 col-md-offset-3">
  <%= render "song_form", song: @song, artists: @artists,
    genres: @genres %>
</div>

app/views/songs/show.html.erb
<% provide :title, @song.name %>
<div class="song-details">
  <h3>
    <span class="song-name"><%= @song.name %></span> -
    <span class="song-artist"><%= @song.artist.name %></span>
  </h3>
</div>
<div class="row">
  <div class="col-md-4">
    <%= image_tag(@song.picture, class: "picture-song") %>
    <audio controls>
      <source src="<%= @song.file %>" type="audio/mpeg">
    </audio>
    <div class="detailBox">
      <div class="titleBox">
        <label><%= t "commentbox" %></label>
      </div>
      <div class="actionBox">
        <ul class="commentList">
          <%= render partial: "comments/comment", collection: @song.comments,
            as: "comment" %>
        </ul>
        <% if logged_in? %>
          <%= render "comments/comment_form", comment: @comment, song: @song %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="fa fa-comments comments_size">
      <%= @song.comments.size %>
    </div>
    <div class="fa fa-star current_rating" >
      <%= @song.total_score.round(2) %>
    </div>
    <% if logged_in? %>
      <%= render "ratings/rating", rating: @rating %>
    <% else %>
      <div>
        <i class="fa fa-star-o"></i>
        <%= link_to t("rating_now"), login_path %>
      </div>
    <% end %>
    <p class="lyric"><%= t ".lyric" %></p>
    <div class="song-lyric">
      <%= @song.lyric %>
    </div>
  </div>
  <% if logged_in? %>
    <% if current_user == @song.user || current_user.is_admin? %>
      <div class="btn-group col-md-2">
        <a class="btn dropdown-toggle btn-info" data-toggle="dropdown" href="#">
          <i class="glyphicon glyphicon-cog"></i>
        </a>
        <ul class="dropdown-menu">
          <li>
            <%= link_to t("edit"), edit_song_path(@song) %>
          </li>
          <li>
            <%= link_to t("delete"), song_path(@song), method: :delete,
              data: {confirm: t("confirm")} %>
          </li>
        </ul>
      </div>
    <% end %>
  <% end %>
</div>